### ISSUE TITLE
Error on small slices

### ISSUE THREAD

**Issue by renankin** [majroy/d3dslic3r#6]
Currently running v.0.3.post2

When working with Stanford Bunny model, I apply uniform scaling 3x and slice with 2 mm increments.

When I try to path 'Slice 201' with 'Path Outline' with 5 mm as average width selected I get the following error:

----
Traceback (most recent call last):
  File "C:\Users\mbgnwrk4\AppData\Roaming\Python\Python312\site-packages\d3dslic3r\slic3_widget.py", line 735, in make_paths
    interior = offset_poly(outline,-self.ui.by_width_sb.value())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbgnwrk4\AppData\Roaming\Python\Python312\site-packages\d3dslic3r\d3dslic3r_common.py", line 427, in offset_poly
    two_d = np.asarray(result[0])
                       ~~~~~~^^^
IndexError: list index out of range

----

When reducing bead width to 0.1 mm it works fine. I think this is happening because the bead width is too big for the given internal slice area. Would it be worth to implement a filter to discard slices which have an area too small based on the input bead width? Currently I am trying to create paths with the expected bead width for WAAM (5-10 mm)

![image](https://github.com/user-attachments/assets/a7eb6514-a0d8-4c05-808c-a0e6b0d73036)

**Comment by renankin** [comment]
Similar issue happens if not using path outline with a too big bead width but another error happens:

Traceback (most recent call last):
  File "C:\Users\mbgnwrk4\AppData\Roaming\Python\Python312\site-packages\d3dslic3r\slic3_widget.py", line 741, in make_paths
    intersections, param = get_intersections(outline,theta,self.ui.by_width_sb.value(),offset)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mbgnwrk4\AppData\Roaming\Python\Python312\site-packages\d3dslic3r\d3dslic3r_common.py", line 336, in get_intersections
    return trans_intersections, (xrange[1]-xrange[0])/width
                                 ~~~~~~^^^
IndexError: index 1 is out of bounds for axis 0 with size 1

**Comment by majroy** [comment]
You are correct, the error is due to the width of the bead relative to the size/shape of the outline.

If your expected bead height is 2 mm with a bead width of 5 mm, then there will be slices in that geometry which will not be able to be infilled. Similarly, there will be slices that have outlines cannot be offset as they result in self-intersecting outlines. If either of these conditions results in slices being discarded, then it will have knock-on effects on the slices above.

I do not have a solution to this unless there is a base resolution that can be identified. For example, what is the shortest possible length of deposition?
